[package]
name = "leo-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[lib]
name = "leo_core"
path = "src/lib.rs"

[dependencies]
serde = { version = "=1.0.229", features = ["derive"] }
toml = "=1.1.5"
toml_edit = "=0.22.22"
